"""Dependency-free DOCX builder for the Lesson 24 alternative resources."""
from pathlib import Path
from zipfile import ZipFile, ZIP_DEFLATED
from xml.sax.saxutils import escape

ROOT=Path(__file__).resolve().parents[1]
def paragraph(text,style='Normal'):
    return f'<w:p><w:pPr><w:pStyle w:val="{style}"/></w:pPr><w:r><w:t xml:space="preserve">{escape(text)}</w:t></w:r></w:p>'
def make_docx(name,title,lines):
    body=''.join(paragraph(x,'Title' if i==0 else ('Heading1' if x.startswith('## ') else 'Normal')) for i,x in enumerate([title]+[x[3:] if x.startswith('## ') else x for x in lines]))
    doc=f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>{body}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1000" w:right="1000" w:bottom="1000" w:left="1000"/></w:sectPr></w:body></w:document>'''
    styles='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:rPr><w:rFonts w:ascii="Arial"/><w:sz w:val="22"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:rPr><w:rFonts w:ascii="Georgia"/><w:b/><w:color w:val="17626D"/><w:sz w:val="40"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="Heading 1"/><w:rPr><w:rFonts w:ascii="Georgia"/><w:b/><w:color w:val="17626D"/><w:sz w:val="28"/></w:rPr></w:style></w:styles>'''
    content='''<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>'''
    rels='''<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>'''
    drels='''<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>'''
    with ZipFile(ROOT/name,'w',ZIP_DEFLATED) as z:
      z.writestr('[Content_Types].xml',content);z.writestr('_rels/.rels',rels);z.writestr('word/document.xml',doc);z.writestr('word/styles.xml',styles);z.writestr('word/_rels/document.xml.rels',drels)
def build():
    reading=['Fiction boundary: Wattle Bay, its people, lantern and events are invented classroom material.','## Noor and the torn map','Noor finds half a map marked with blue lanterns in the old signal shed. It may show an old Lantern Walk route, but the map ends before the harbour steps. She sends a photograph to Eli and calls it a clue, not proof.','## Eli and the quiet light','Eli repairs part of the lantern. It glows, then flickers. He lists what still needs to happen: a safety check, a bracket and council inspection. He has not shown it to anyone yet.','## Mrs Vale and the paused walk','Mrs Vale pauses the Lantern Walk while the old path is checked. She says the map may show another route, but it is not a decision. The council still needs to inspect the path and lantern.','## Reader guide','Evidence = directly stated. Inference = what the clues may mean. Prediction = a possible future. Condition = what must happen first.','Supported: Noor’s map could help people consider another route. Overclaim: The council has approved the walk.','Write one forecast that uses a clue from Noor, Eli and Mrs Vale, then add a condition.']
    organiser=['Name: ______________________________ Date: __________','## 1. Collect three clues','Noor evidence: __________________________________________________________','What it may mean: _______________________________________________________','Eli evidence: ___________________________________________________________','What it may mean: _______________________________________________________','Mrs Vale evidence: ______________________________________________________','What it may mean: _______________________________________________________','## 2. Build a careful forecast','Because __________________________________________________________________','Together, these clues could ______________________________________________','This remains uncertain because / if ________________________________________','## 3. Draft and revise','Write 8-10 sentences. Include three accurate details, two reasoning links, cautious language and one condition.','Overconfident: The Lantern Walk will happen tomorrow.','Careful revision: The Lantern Walk could happen on a changed route if the path and lantern are checked.','Final check: [ ] three clues [ ] connection [ ] cautious word [ ] condition [ ] no unshown event presented as fact']
    concise=['Same big idea: use clues to say what might happen.','## Three clues','Noor found part of a map. It could help people look for another route.','Eli fixed part of the lantern. It might be useful after a check.','Mrs Vale paused the walk. She may decide after the path check.','## Say my forecast','Because Noor found __________________________ and Eli repaired __________________________,','the walk could ___________________________________________________________.','This may happen if ______________________________________________________.','We do not know yet because ______________________________________________.','You may point, say, copy or ask a partner to scribe.']
    make_docx('Lesson_24_Signal_Lantern_Reading_Pack.docx','The Signal Lantern: Reading Pack',reading);make_docx('Lesson_24_Signal_Lantern_Forecast_Organiser.docx','The Signal Lantern: Forecast Organiser',organiser);make_docx('Lesson_24_Signal_Lantern_Concise_Access_Pack.docx','The Signal Lantern: Concise Access Pack',concise)
if __name__=='__main__':build();print('Built three DOCX resources')
