/* Authoritative builder for the Harbour Light alternative. */
const fs = require('fs');
const path = require('path');
const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, WidthType, BorderStyle } = require('docx');
const { chromium } = require('playwright');
const ROOT = path.resolve(__dirname, '..');
const ASSETS = path.join(ROOT, 'assets');
const WORKSPACE = path.resolve(ROOT, '..', '..', '..', '..', '..', '..');
const COMPILER = path.join(WORKSPACE, '.agents', 'skills', 'lesson-creator', 'scripts', 'compile_presentation.py');
const PY = 'python';
const article = [
 ['A warning no one could ignore', 'On the afternoon of the Bay Festival, the lantern on the old Harbour Light Jetty went dark. The jetty was not open to visitors after the storm, but the unlit lantern mattered: it marked the shallow channel that the community fishing boats used to return home. At first, people gathered on the foreshore and waited for an adult to solve it. Then Nia noticed something else: a small rescue dinghy had become caught in drifting rope near the jetty steps.'],
 ['The choice', 'Nia had been collecting rubbish for the festival clean-up with her cousin, Ravi. They could see the rope tightening whenever the tide pushed the dinghy sideways. Ravi wanted to run straight onto the jetty. Nia stopped him. The storm had loosened boards and the waves were still high. Instead, she used the public emergency phone beside the kiosk, described the rope, the dark lantern and the position of the dinghy, and asked the festival coordinator to keep people back from the water.'],
 ['Courage is not careless', 'While they waited, Nia did not pretend she felt calm. She worried that the dinghy would scrape against the pylons and that people would blame them for not doing more. Still, she kept giving clear updates. When the marine rescue crew arrived, they used a long pole and safety line to free the dinghy. A technician restored the lantern before dusk. The important turning point was not a dramatic leap onto the jetty. It was Nia choosing a safe action that made expert help possible.'],
 ['What changed afterwards', "The next week, the festival committee proposed a 'Look, Call, Clear' sign near the foreshore. The sign would remind visitors to notice hazards, call for help and keep a safe space clear for trained responders. Some residents said a sign would be unnecessary because adults already know what to do. Others worried that the message might make children feel responsible for emergencies. Nia's account offered a more careful idea: a sign cannot replace adults or trained crews, but it can help everyone recognise when stopping, reporting and making room is a brave kind of action."],
 ['A claim worth sharing', "The Harbour Light story suggests that courage is not always loud. It can mean noticing a real problem, accepting that you cannot solve it alone and taking the next safe step. That idea matters beyond the jetty. A community works better when people do not ignore a risk simply because they feel unsure. The proposed sign should be trialled for the next festival because it turns one frightening moment into a practical invitation: see the problem, seek help and leave space for others to act safely."]
];
const text = (value, size=20, bold=false, colour='173D45') => new TextRun({text:value, font:'Aptos', size, bold, color:colour});
const p = (value='', opt={}) => new Paragraph({spacing:{after:opt.after ?? 110, before:opt.before ?? 0, line:240}, children:[text(value,opt.size ?? 20,opt.bold ?? false,opt.colour ?? '173D45')]});
const cell = (value, header=false) => new TableCell({width:{size:3120,type:WidthType.DXA}, shading:header?{fill:'123E4A'}:undefined, margins:{top:120,bottom:120,left:140,right:140}, borders:{top:{style:BorderStyle.SINGLE,color:'B8D0D1',size:4},bottom:{style:BorderStyle.SINGLE,color:'B8D0D1',size:4},left:{style:BorderStyle.SINGLE,color:'B8D0D1',size:4},right:{style:BorderStyle.SINGLE,color:'B8D0D1',size:4}}, children:[p(value,{size:19,bold:header,colour:header?'FFFFFF':'173D45',after:0})]});
function table(headers, rows){return new Table({width:{size:9360,type:WidthType.DXA},rows:[new TableRow({children:headers.map(x=>cell(x,true))}),...rows.map(row=>new TableRow({children:row.map(x=>cell(x))}))]});}
function base(children){return new Document({sections:[{properties:{page:{margin:{top:850,bottom:850,left:980,right:980}}},children}]});}
function title(kicker, title, subtitle){return [p(kicker.toUpperCase(),{size:17,bold:true,colour:'A15C3B',after:30}),p(title,{size:44,bold:true,colour:'123E4A',after:30}),p(subtitle,{size:21,colour:'476D72',after:220})];}
async function writeDocx(name, doc){fs.writeFileSync(path.join(ROOT,name), await Packer.toBuffer(doc));}
function readingDoc(){let c=[...title('English Unit 3 | Lesson 25 alternative','When the Lantern Went Dark','A fictional community feature about an emergency, a difficult choice and what courage can persuade us to do next.'),p('This is an original fictional text. Treat its events as material for close reading, not as real-world evidence.',{size:18,bold:true,colour:'7C4C17',after:160})];article.forEach(([h,b])=>c.push(p(h,{size:27,bold:true,colour:'21626A',before:90,after:30}),p(b,{size:20,after:100})));c.push(p('Reading trail',{size:27,bold:true,colour:'21626A',before:100,after:50}),table(['Find','Copy or paraphrase','What it helps you claim'],[['Turning point','Nia calls for trained help instead of entering the jetty.','Courage can include safe, deliberate action.'],['Consequence','The rescue crew can free the dinghy and restore the light.','One choice can make another action possible.'],['Future action',"The committee proposes a 'Look, Call, Clear' sign.",'A story can become a persuasive proposal.']]),p('Talk before you write',{size:27,bold:true,colour:'21626A',before:130,after:40}),p('1. Which moment is the climax? Defend your choice.',{size:20}),p('2. How does Nia show care without pretending she can solve the emergency alone?',{size:20}),p('3. Which detail could support a persuasive claim about courage? Explain the link.',{size:20}));return base(c);}
function organiser(concise=false){let c=[...title('English Unit 3 | Lesson 25 alternative','Turning point to persuasive claim','Plan a short paragraph that explains why a brave choice matters to a reader.')];if(concise){c.push(p('You can point, speak, copy, draw an arrow or use a partner scribe.',{size:21,bold:true,colour:'7C4C17',after:140}),table(['What happened?','What did Nia do?','What changed?'],[['The lantern went dark. The dinghy was stuck.','She used the emergency phone and asked people to stay back.','The rescue crew could help safely.']]),p('My claim',{size:27,bold:true,colour:'21626A',before:130}),p('Courage can mean ________________________________________________.',{size:23,after:160}),p('Why it matters',{size:27,bold:true,colour:'21626A'}),p('This matters because ______________________________________________.',{size:23,after:160}),p('Say or write',{size:27,bold:true,colour:'21626A'}),p('Nia was brave when _______________________________________________.',{size:23}),p('This shows that courage can _______________________________________.',{size:23}),p('□ point   □ speak   □ copy   □ partner scribe',{size:18,bold:true,colour:'476D72',after:0}));}else{c.push(p('1. Zoom in on the turning point',{size:27,bold:true,colour:'21626A',before:40}),table(['Precise event','Character decision','Consequence'],[['','','']]),p('2. Build a defensible claim',{size:27,bold:true,colour:'21626A',before:130}),table(['Evidence detail','Claim about courage','Why a reader should care'],[['','','']]),p('3. Draft and revise (6-8 sentences)',{size:27,bold:true,colour:'21626A',before:130}),p('Start with the event. Explain the decision and consequence. Make a claim about courage. Use one detail. End with why the claim matters to a reader.',{size:20,bold:true,after:120}),...Array.from({length:6},()=>p('________________________________________________________________________________',{size:20,colour:'476D72',after:100})),p('Revision check: □ precise event  □ consequence  □ evidence  □ claim  □ reader purpose',{size:18,bold:true,colour:'476D72',after:0}));}return base(c);}
function teacherDoc(){let c=[...title('Teacher guide | Lesson 25 alternative','Harbour Light: Climax to Claim','A 50-minute original-text lesson that bridges narrative meaning to persuasive writing.'),p('Teaching focus',{size:27,bold:true,colour:'21626A'}),p("Students move from recounting an event to explaining how a character's choice changes what is possible, then use that interpretation as the centre of a short persuasive claim. The fictional reading keeps the focus on reasoning rather than factual research.",{size:20}),p('Model answer',{size:27,bold:true,colour:'21626A',before:100}),p("When the Harbour Light Jetty lantern goes dark and a rescue dinghy catches in rope, Nia chooses to call for trained help rather than enter the unsafe jetty. Her decision lets the rescue crew work safely and restore the light before dusk. This suggests that courage can mean taking the responsible next step even when you feel afraid or cannot solve a problem alone. Nia does not ignore the danger, but she also does not act carelessly. Her choice matters because readers may think bravery always means doing the dramatic thing. The proposed 'Look, Call, Clear' sign should be trialled because it turns that lesson into a practical reminder for the whole community.",{size:20}),p('Misconceptions to surface',{size:27,bold:true,colour:'21626A',before:100}),table(['Likely idea','Responsive prompt'],[['The climax is simply the most exciting event.','Which event changes what can happen next?'],['Bravery means acting without fear.','What does Nia feel, and what does she choose despite that feeling?'],['A claim is a plot summary.','What broader idea does this event suggest to a reader?'],['The story proves a real fact about emergencies.','What is fictional here? What evidence would a real proposal need?']]),p('Answer guidance',{size:27,bold:true,colour:'21626A',before:100}),p("The strongest climax choice is Nia's emergency call because it redirects the response from unsafe impulse to expert action. Accept another choice only if a student explains how it changes the direction of events. Strong claims are interpretations, not a single correct theme. They should include a precise event, a consequence, a cautious statement about courage and a reader purpose.",{size:20}),p('Access and extension',{size:27,bold:true,colour:'21626A',before:100}),p("Green view and concise organiser: reduce language load, retain the same event-to-claim pathway, allow oral/pointing/scribed responses. Extension: use 'can' or 'may', and explain why a community sign is a proposal rather than proof that every reader will act safely.",{size:20})];return base(c);}
function articleHtml(){return `<!doctype html><html lang="en-AU"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>When the Lantern Went Dark</title><style>@page{size:A4;margin:17mm 18mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#173d45;line-height:1.43;margin:0}.k{font-size:9px;font-weight:800;letter-spacing:1.4px;color:#a15c3b}.title{font:700 32px/1.1 Georgia,serif;color:#123e4a;margin:5px 0}.deck{font-size:12px;color:#476d72;margin:0 0 12px}.boundary{background:#fff3df;border-left:5px solid #a15c3b;padding:8px 10px;font-size:10px;font-weight:bold}.heading{font:700 17px Georgia,serif;color:#21626a;margin:15px 0 3px}p{font-size:11px;margin:0 0 8px}.talk{break-inside:avoid;background:#eaf3f3;padding:10px 12px;border-radius:7px;margin-top:10px}.talk b{color:#21626a}.talk p{margin:4px 0}@media print{.talk{break-inside:avoid}}</style><body><div class="k">ENGLISH UNIT 3 | LESSON 25 ALTERNATIVE</div><h1 class="title">When the Lantern Went Dark</h1><p class="deck">A fictional community feature about an emergency, a difficult choice and what courage can persuade us to do next.</p><p class="boundary">This is an original fictional text. Treat its events as material for close reading, not as real-world evidence.</p>${article.map(([h,b])=>`<h2 class="heading">${h}</h2><p>${b}</p>`).join('')}<section class="talk"><b>Talk before you write</b><p>1. Which moment is the climax? Defend your choice.</p><p>2. How does Nia show care without pretending she can solve the emergency alone?</p><p>3. Which detail could support a persuasive claim about courage? Explain the link.</p></section></body></html>`;}
function makePdf(){const html=path.join(ROOT,'Lesson_25_Harbour_Light_Reading_Article.html');fs.writeFileSync(html,articleHtml());const lines=['ENGLISH UNIT 3 | LESSON 25 ALTERNATIVE','WHEN THE LANTERN WENT DARK','A fictional community feature about an emergency, a difficult choice and courage.',...article.flatMap(([h,b])=>[h,...(b.match(/.{1,88}(?:\\s|$)/g)||[b]).map(x=>x.trim())]),'Talk before you write','1. Which moment is the climax? Defend your choice.','2. How does Nia show care without pretending she can solve the emergency alone?','3. Which detail could support a persuasive claim about courage? Explain the link.'];let pages=[],current=[],y=790;for(const line of lines){const big=line===lines[1],heading=article.some(([h])=>h===line)||line==='Talk before you write';const size=big?22:heading?13:line===lines[0]?8:10.5;const step=big?31:heading?21:15;if(y<65){pages.push(current);current=[];y=790;}const colour=big?'0.07 0.24 0.29':heading?'0.13 0.38 0.42':line===lines[0]?'0.63 0.36 0.23':'0.09 0.24 0.27';const safe=line.split('\\').join('\\\\').split('(').join('\\(').split(')').join('\\)');current.push(`BT /F1 ${size} Tf ${colour} rg 52 ${y} Td (${safe}) Tj ET`);y-=step;}pages.push(current);const objs=[];const add=s=>{objs.push(s);return objs.length;};const font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');const pageRefs=[];for(const content of pages){const stream=content.join('\\n');const contentRef=add(`<< /Length ${Buffer.byteLength(stream)} >>\\nstream\\n${stream}\\nendstream`);pageRefs.push(add(`<< /Type /Page /Parent PAGESREF /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${font} 0 R >> >> /Contents ${contentRef} 0 R >>`));}const pagesRef=add(`<< /Type /Pages /Kids [${pageRefs.map(x=>x+' 0 R').join(' ')}] /Count ${pageRefs.length} >>`);const catalog=add(`<< /Type /Catalog /Pages ${pagesRef} 0 R >>`);let body='%PDF-1.4\\n';const offsets=[0];objs.forEach((o,i)=>{offsets.push(Buffer.byteLength(body));body+=`${i+1} 0 obj\\n${o.replace(/PAGESREF/g,`${pagesRef} 0 R`)}\\nendobj\\n`;});const xref=Buffer.byteLength(body);body+=`xref\\n0 ${objs.length+1}\\n0000000000 65535 f \\n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n ').join('\\n')}\\ntrailer << /Size ${objs.length+1} /Root ${catalog} 0 R >>\\nstartxref\\n${xref}\\n%%EOF`;fs.writeFileSync(path.join(ROOT,'Lesson_25_Harbour_Light_Reading_Article.pdf'),body);}
async function main(){await writeDocx('Lesson_25_Harbour_Light_Reading_Pack.docx',readingDoc());await writeDocx('Lesson_25_Harbour_Light_Organiser.docx',organiser());await writeDocx('Lesson_25_Harbour_Light_Concise_Access_Pack.docx',organiser(true));await writeDocx('Lesson_25_Harbour_Light_Teacher_Guide.docx',teacherDoc());require('child_process').execFileSync(PY,[COMPILER,'--slides',path.join(ASSETS,'harbour_light_slides.html'),'--css',path.join(ASSETS,'harbour_light.css'),'--js',path.join(ASSETS,'harbour_light.js'),'--output',path.join(ROOT,'Lesson_25_Harbour_Light_Presentation.html'),'--title','Lesson 25 | Harbour Light: Climax to Claim','--language','en-AU'],{stdio:'inherit'});await makePdf();}
main().catch(error=>{console.error(error);process.exit(1);});
