const path=require('path'),fs=require('fs');
const {Document,Packer,Paragraph,TextRun,Table,TableRow,TableCell,WidthType,BorderStyle,ShadingType,AlignmentType,Header,Footer,PageBreak}=require('docx');
const ROOT=path.resolve(__dirname,'..'),W=10178,C={ink:'173B3A',navy:'183E4A',teal:'3F7D72',coral:'A84F3A',gold:'D69743',pale:'E8F2E9',warm:'FFF1D8',border:'AFC5BE',muted:'5E7470'};
const p=(t='',o={})=>new Paragraph({spacing:{after:o.after??90,line:o.line??245},alignment:o.align,children:[new TextRun({text:t,font:'Calibri',size:Math.round((o.size??10.5)*2),bold:o.bold,color:o.color??C.ink,italics:o.italics})]});
const cell=(t,w,fill='FFFFFF')=>new TableCell({width:{size:w,type:WidthType.DXA},shading:{fill,type:ShadingType.CLEAR},margins:{top:100,bottom:100,left:120,right:120},borders:{top:{style:BorderStyle.SINGLE,size:4,color:C.border},bottom:{style:BorderStyle.SINGLE,size:4,color:C.border},left:{style:BorderStyle.SINGLE,size:4,color:C.border},right:{style:BorderStyle.SINGLE,size:4,color:C.border}},children:[p(t,{size:9.2,bold:fill===C.navy,color:fill===C.navy?'FFFFFF':C.ink,after:0})]});
const table=(h,rows,widths)=>new Table({width:{size:W,type:WidthType.DXA},columnWidths:widths,rows:[new TableRow({tableHeader:true,children:h.map((x,i)=>cell(x,widths[i],C.navy))}),...rows.map(r=>new TableRow({children:r.map((x,i)=>cell(x,widths[i]))}))]});
const call=(l,t,fill=C.pale)=>new Table({width:{size:W,type:WidthType.DXA},rows:[new TableRow({children:[new TableCell({shading:{fill,type:ShadingType.CLEAR},margins:{top:110,bottom:110,left:150,right:150},borders:{left:{style:BorderStyle.SINGLE,size:18,color:C.teal}},children:[p(l,{size:10.2,bold:true,color:C.coral,after:20}),p(t,{size:10.1,after:0})]})]})]});
const base=(label,children)=>new Document({creator:'Joshua English Unit 3',title:label,sections:[{properties:{page:{size:{width:11906,height:16838},margin:{top:864,right:864,bottom:864,left:864,header:360,footer:360}}},headers:{default:new Header({children:[p('ENGLISH UNIT 3 | LESSON 29 ALTERNATIVE',{size:7.5,bold:true,color:C.muted,align:AlignmentType.RIGHT,after:0})]})},footers:{default:new Footer({children:[p(label+' | The Harbour Garden',{size:7.5,color:C.muted,align:AlignmentType.CENTER,after:0})]})},children}]});
const title=(k,t,s,l)=>[p(k,{size:8.5,bold:true,color:C.coral,after:55}),p(t,{size:23,bold:true,color:C.navy,after:55}),p(s,{size:11,italics:true,color:C.muted,after:120}),p(l,{size:8.5,bold:true,color:C.teal,after:170})];const h=t=>p(t,{size:15,bold:true,color:C.navy,after:100}); const blanks=(h,w,n=3)=>table(h,Array.from({length:n},()=>h.map(()=>"\n\n")),w);
async function save(n,d){fs.writeFileSync(path.join(ROOT,n),await Packer.toBuffer(d));console.log(n)}
async function reading(){let c=[...title('ORIGINAL CLASSROOM FEATURE','The Harbour Garden Proposal','A model conclusion that makes a future visible without over-promising.','READ | MARK RETURN / FUTURE / ACTION'),call('Fiction boundary','Harbourview and all details are invented for craft analysis. They are not research evidence.',C.warm),h('A corner with a next step'),p('At Harbourview School, the paved corner beside the library is usually empty at lunch. The student garden team imagines two donated planters, shade from a sail and a table where students could sketch, read or wait for a friend.'),call('Thesis','Harbourview School should run a six-week Harbour Garden trial beside the library, then decide whether the space is useful and manageable.'),p('The proposal adds a choice; it does not ask every student to garden. Some people may worry that a garden could cost too much or become untidy. That is a fair concern.'),call('Measured response','The trial could begin with donated planters, a simple sign-out tub and a weekly duty-teacher check. The team could record what works before asking for a longer commitment.'),new Paragraph({children:[new PageBreak()]}),h('Ending with a future readers can picture'),call('Model conclusion','Harbourview should approve a six-week Harbour Garden trial near the library. With a small, carefully managed space, the corner could become a place where students can read, draw or talk quietly at lunch. The principal can begin by approving the trial and asking the garden team to record what works before a longer decision is made.',C.warm),p('The word could shows a possible future, not a guarantee. A persuasive ending returns to the position, makes a future visible and asks an audience for one specific action.'),h('Reading check'),p('1. Restate the proposal.\n2. Underline the fair concern.\n3. Circle the conditional word.\n4. Who acts first?\n5. Replace this overclaim: “The garden will make everyone happy.”'),call('Source note','Use your own traceable, checked sources for an assessment claim. This feature supplies a conclusion pattern only.')];return save('Lesson_29_Harbour_Garden_Reading_Pack.docx',base('Reading Pack',c))}
async function organiser(){let c=[...title('PERSUASIVE WRITING ORGANISER','My conclusion: a future with a next step','Plan, write and revise a conclusion that earns its hope.','PLAN | DRAFT | TEST'),h('1. Make three decisions'),blanks(['Return to my opinion','Future I want to make possible','Action my audience can take'],[3392,3392,3394],2),h('2. Draft my conclusion'),p('________________________________________________________________________________\n________________________________________________________________________________\n________________________________________________________________________________\n________________________________________________________________________________',{size:12}),h('3. Reader test'),table(['My reader can say...','Yes / not yet','Revision I will make'],[['Who should act?','',''],['What could change?','',''],['Why this is believable?','','']],[3900,1850,4428]),call('Final check','[ ] I return to my opinion.  [ ] I use a possible, not guaranteed, future.  [ ] I name a specific next action.',C.warm)];return save('Lesson_29_Harbour_Garden_Conclusion_Organiser.docx',base('Conclusion Organiser',c))}
async function concise(){let c=[...title('CONCISE ACCESS PACK','A hopeful ending','Same goal: say what should happen, what could change and what to do first.','POINT | SAY | DRAW | WRITE'),h('The model idea'),p('The school could try a small garden near the library for six weeks. Students could use the space to read, draw or talk quietly. The principal could say yes to the trial and then check how it works.',{size:13}),h('Build my ending'),p('I think __________________ should ________________________________.\n\nThis could help _________________________________________________.\n\nFirst, __________________ can __________________________________.\n\nMy ending: _____________________________________________________.',{size:13}),call('Check','Point to or tick: [ ] opinion  [ ] possible future  [ ] action',C.warm),h('Say it first'),p('Tell a partner: “I think ____. This could ____. First, ____ can ____.”',{size:13})];return save('Lesson_29_Harbour_Garden_Concise_Access_Pack.docx',base('Concise Access Pack',c))}
Promise.all([reading(),organiser(),concise()]).catch(e=>{console.error(e);process.exitCode=1});
