(() => {
  const cfg = window.FestivalConfig;
  const STORE = "festival-day-state-v1";
  const app = document.querySelector("#app");
  const username = document.querySelector("#username");
  const saveStatus = document.querySelector("#save-status");
  const approvalDialog = document.querySelector("#approval-dialog");
  const filmDialog = document.querySelector("#film-dialog");
  const groups = [window.FestivalEnglishHass, window.FestivalMaths, window.FestivalScience, window.FestivalSynthesis].filter(Boolean);
  const missions = groups.flatMap(group => group.missions || []).sort((a,b) => a.film - b.film);
  let view = "map", activeId = null, storageOK = true;
  let state = { schemaVersion:"1.0", exportType:"festival_day_student_dossier", appVersion:cfg.appVersion, contentVersion:cfg.contentVersion, submissionId:cryptoId(), startedAt:new Date().toISOString(), username:"", responses:{}, approvals:{}, requestedChanges:{}, savedAt:null };

  function cryptoId(){ return (crypto.randomUUID ? crypto.randomUUID() : `festival-${Date.now()}-${Math.random().toString(16).slice(2)}`); }
  function missionById(id){ return missions.find(m => m.id === id); }
  function safeStorageGet(){ try { return localStorage.getItem(STORE); } catch (_) { storageOK=false; return null; } }
  function save(){ state.username=username.value.trim(); state.savedAt=new Date().toISOString(); try { localStorage.setItem(STORE, JSON.stringify(state)); storageOK=true; } catch (_) { storageOK=false; } saveStatus.textContent = storageOK ? `Saved on this device at ${new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}. Download a checkpoint before closing.` : "Browser saving is unavailable. Download a checkpoint before closing."; }
  function load(){ const saved=safeStorageGet(); if (!saved) return; try { const parsed=JSON.parse(saved); if (parsed && parsed.schemaVersion==="1.0") state={...state,...parsed,responses:parsed.responses||{},approvals:parsed.approvals||{},requestedChanges:parsed.requestedChanges||{}}; } catch (_) { saveStatus.textContent="A saved draft could not be read. Start a new dossier or import a checkpoint."; } }
  function responseFor(id){ return state.responses[id] || (state.responses[id]={ answers:{}, writing:"", notebook:"" }); }
  function readText(value){ if (Array.isArray(value)) return value.join("\n\n"); if (typeof value === "object" && value) return value.paragraphs ? value.paragraphs.join("\n\n") : Object.values(value).filter(v=>typeof v==="string").join("\n\n"); return value || ""; }
  function sourceText(source){ return readText(source?.text) || source?.claim || source?.detail || source?.description || ""; }
  function questionKind(q){ const kind=q.kind||q.type||"text"; return ({numeric:"number",response:"text",shortText:"text"})[kind]||kind; }
  function questionAnswered(q, value){ return questionKind(q)==="choice" ? Boolean(value) : String(value||"").trim().length>0; }
  function requiredComplete(m){ const r=state.responses[m.id]; return Boolean(r) && m.questions.every(q=>questionAnswered(q,r.answers?.[q.id])) && String(r.writing||"").trim().length>0; }
  function status(m){ if(state.approvals[m.id]) return "Approved"; if(state.requestedChanges[m.id]) return "Changes requested"; if(requiredComplete(m)) return "Ready for teacher"; const r=state.responses[m.id]; return r ? "In progress" : "Not started"; }
  function statusClass(m){ const s=status(m); return s==="Approved"?"approved":s==="Ready for teacher"?"ready":s==="Changes requested"?"changes":""; }
  function escapeHtml(value){ return String(value??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"})[c]); }
  function renderMap(){
    const core=missions.filter(m=>m.type==="core" || m.extension===false), ext=missions.filter(m=>!(m.type==="core" || m.extension===false));
    const approved=Object.keys(state.approvals).length, pct=Math.round((approved/missions.length)*100);
    app.innerHTML=`<section class="panel"><h2>Your festival dossier</h2><p>Complete a mission, show it to your teacher, then earn its numbered film. Your answers will help with the final committee hearing.</p><div class="progress" aria-label="${approved} of ${missions.length} missions approved"><i style="width:${pct}%"></i></div><p class="small">${approved} of ${missions.length} missions approved. Your teacher decides when each film is earned.</p></section><h2>Core missions</h2><div class="grid">${core.map(card).join("")}</div><h2>Extra challenge cases</h2><p class="small">Try these when your teacher says you are ready. They earn films 7–12.</p><div class="grid">${ext.map(card).join("")}</div>`;
    app.querySelectorAll("[data-open]").forEach(b=>b.addEventListener("click",()=>{activeId=b.dataset.open;view="mission";render();}));
    app.querySelectorAll("[data-film]").forEach(b=>b.addEventListener("click",()=>openFilm(Number(b.dataset.film))));
  }
  function card(m){ const s=status(m), approval=state.approvals[m.id]; return `<article class="card mission-card"><span class="status ${statusClass(m)}">${s}</span><h2>${escapeHtml(m.title)}</h2><p>${escapeHtml(m.brief)}</p><p class="small">Reward: Film ${m.film}</p><button data-open="${m.id}">${approval?"Review work":"Open mission"}</button>${approval?`<button class="secondary" data-film="${m.film}">Watch Film ${m.film}</button>`:""}</article>`; }
  function renderMission(){ const m=missionById(activeId), r=responseFor(m.id), approved=state.approvals[m.id]; const reading=readText(m.reading?.main); const support=readText(m.reading?.support); app.innerHTML=`<div class="toolbar"><button class="secondary" id="back">← Mission map</button><div><span class="status ${statusClass(m)}">${status(m)}</span> <span class="small">Reward: Film ${m.film}</span></div></div><section class="mission-head panel"><div><h2>${escapeHtml(m.title)}</h2><p>${escapeHtml(m.brief)}</p></div><button id="support-toggle" class="secondary">Show simpler reading</button></section><div class="mission-layout"><article class="panel"><h2>Evidence file</h2><div id="main-reading" class="reading">${escapeHtml(reading)}</div><div id="support-reading" class="reading hidden">${escapeHtml(support)}</div>${(m.sources||[]).map(s=>`<div class="source"><strong>${escapeHtml(s.label||"Source")}</strong><br>${escapeHtml(sourceText(s))}</div>`).join("")}<p class="small">${escapeHtml(m.sourceNote||"")}</p></article><article class="panel"><h2>Build your case</h2><p class="small">Answer each question, then write your recommendation. Your teacher will review it.</p>${m.questions.map(q=>questionMarkup(q,r.answers[q.id])).join("")}<section class="writing"><h3>Recommendation</h3><p>${escapeHtml(m.writing?.prompt||"")}</p><p class="stems">Optional starters: ${(m.writing?.stems||[]).map(escapeHtml).join(" ")}</p><textarea id="writing" aria-label="Recommendation" placeholder="Write your response here...">${escapeHtml(r.writing)}</textarea></section><section class="writing"><h3>Evidence notebook</h3><p class="small">Keep a useful fact, calculation or idea for the final mission.</p><textarea id="notebook" aria-label="Evidence notebook" placeholder="I may use this later...">${escapeHtml(r.notebook)}</textarea></section><section class="writing"><h3>Check before you show your teacher</h3><ul class="criteria">${(m.criteria||[]).map(c=>`<li>${escapeHtml(c)}</li>`).join("")}</ul>${state.requestedChanges[m.id]?`<p class="notice"><strong>Teacher note:</strong> ${escapeHtml(state.requestedChanges[m.id].note||"Please revise and show your teacher again.")}</p>`:""}</section><div class="actions"><button id="save-mission" class="secondary">Save checkpoint</button><button id="teacher-review" ${requiredComplete(m)?"":"disabled"}>${approved?"See approval":"Ready for teacher"}</button>${approved?`<button id="watch-film" class="secondary">Watch Film ${m.film}</button>`:""}</div><p id="mission-message" class="small" aria-live="polite"></p></article></div>`;
    document.querySelector("#back").onclick=()=>{view="map";render();}; document.querySelector("#support-toggle").onclick=()=>{document.querySelector("#main-reading").classList.toggle("hidden");document.querySelector("#support-reading").classList.toggle("hidden");};
    document.querySelectorAll("[data-question]").forEach(el=>el.addEventListener("input",()=>{r.answers[el.dataset.question]=el.type==="radio"?el.value:el.value; save(); renderQuestionFeedback(m,el.dataset.question); updateReady(m); }));
    document.querySelectorAll("input[type=radio][data-question]").forEach(el=>el.addEventListener("change",()=>{r.answers[el.dataset.question]=el.value;save();renderQuestionFeedback(m,el.dataset.question);updateReady(m);}));
    ["writing","notebook"].forEach(id=>document.querySelector(`#${id}`).addEventListener("input",e=>{r[id]=e.target.value;save();updateReady(m);}));
    m.questions.forEach(q=>renderQuestionFeedback(m,q.id)); document.querySelector("#save-mission").onclick=download; document.querySelector("#teacher-review").onclick=()=>openApproval(m); if(approved) document.querySelector("#watch-film").onclick=()=>openFilm(m.film);
  }
  function optionValue(option,index){ return typeof option==="object" ? String(option.value ?? index) : String(option); }
  function optionLabel(option){ return typeof option==="object" ? String(option.label ?? option.value) : String(option); }
  function questionMarkup(q,value){ const kind=questionKind(q); if(kind==="choice") return `<section class="question"><label>${escapeHtml(q.prompt)}</label><div class="options">${(q.options||[]).map((o,i)=>{const v=optionValue(o,i);return `<label><input type="radio" name="${q.id}" data-question="${q.id}" value="${escapeHtml(v)}" ${String(value)===v?"checked":""}> ${escapeHtml(optionLabel(o))}</label>`;}).join("")}</div><div id="feedback-${q.id}"></div></section>`; const input=kind==="number"?`<input data-question="${q.id}" type="text" inputmode="decimal" value="${escapeHtml(value||"")}" placeholder="${escapeHtml(q.placeholder||"Enter your answer")}">`:`<textarea data-question="${q.id}" placeholder="${escapeHtml(q.placeholder||"Write your answer")}">${escapeHtml(value||"")}</textarea>`; return `<section class="question"><label>${escapeHtml(q.prompt)}</label>${input}<div id="feedback-${q.id}"></div></section>`; }
  function normalise(value){ return String(value??"").toLowerCase().replace(/\s+/g," ").trim(); }
  function feedbackText(feedback,correct){ if(typeof feedback==="object"&&feedback) return correct ? (feedback.correct||"Good evidence choice.") : (feedback.incorrect||"Look back at the evidence, then try again."); return feedback|| (correct?"Good evidence choice.":"Look back at the evidence, then try again."); }
  function answerMatches(q,value){ let expected=q.answer; if(questionKind(q)==="choice"&&Number.isInteger(expected)&&q.options?.[expected]!==undefined) expected=optionValue(q.options[expected],expected); const actual=normalise(value); if(Array.isArray(expected)) return expected.map(normalise).includes(actual); return actual===normalise(expected); }
  function renderQuestionFeedback(m,qid){ const q=m.questions.find(x=>x.id===qid), box=document.querySelector(`#feedback-${qid}`), value=responseFor(m.id).answers[qid],kind=questionKind(q); if(!box||value===undefined||value==="") return; if(kind!=="choice"&&kind!=="number"){box.innerHTML="<p class='feedback'>Saved for teacher review. Use the evidence and success criteria to improve it.</p>";return;} if(q.answer===undefined)return; const correct=answerMatches(q,value),feedback=correct?(q.feedbackCorrect||feedbackText(q.feedback,true)):feedbackText(q.feedback,false); box.innerHTML=`<p class="feedback ${correct?"":"bad"}"><strong>${correct?"Check complete":"Check again"}</strong> ${escapeHtml(feedback)}</p>`; }
  function updateReady(m){ const button=document.querySelector("#teacher-review"); if(button) button.disabled=!requiredComplete(m); const msg=document.querySelector("#mission-message"); if(msg) msg.textContent=requiredComplete(m)?"Your work is ready to show your teacher.":"Finish every response and your recommendation before asking your teacher."; }
  function openApproval(m){ const r=responseFor(m.id); document.querySelector("#approval-summary").textContent=`Review ${m.title} for ${state.username||"this student"}. Approval unlocks Film ${m.film}.`; document.querySelector("#approval-work").innerHTML=`<p><strong>Recommendation:</strong></p><p>${escapeHtml(r.writing).replace(/\n/g,"<br>")}</p><p><strong>Criteria:</strong> ${(m.criteria||[]).map(escapeHtml).join(" · ")}</p>`; document.querySelector("#teacher-note").value="";document.querySelector("#pin").value="";document.querySelector("#pin-area").classList.add("hidden");document.querySelector("#pin-message").textContent="";approvalDialog.dataset.mission=m.id; approvalDialog.showModal(); }
  document.querySelector("#close-approval").onclick=()=>approvalDialog.close(); document.querySelector("#open-pin").onclick=()=>{document.querySelector("#pin-area").classList.remove("hidden");document.querySelector("#pin").focus();}; document.querySelector("#request-changes").onclick=()=>{const id=approvalDialog.dataset.mission;state.requestedChanges[id]={note:document.querySelector("#teacher-note").value.trim(),at:new Date().toISOString()};save();approvalDialog.close();render();}; document.querySelector("#confirm-pin").onclick=()=>{const entered=document.querySelector("#pin").value;const id=approvalDialog.dataset.mission;if(entered!==cfg.teacherPin){document.querySelector("#pin-message").textContent="PIN not accepted. No approval was recorded.";return;} const m=missionById(id),r=responseFor(id);state.approvals[id]={approvedAt:new Date().toISOString(),approvedRevision:state.savedAt||new Date().toISOString(),film:m.film,snapshot:JSON.parse(JSON.stringify(r))};delete state.requestedChanges[id];save();approvalDialog.close();render();};
  function openFilm(number){ document.querySelector("#film-title").textContent=`Film ${number}`; const vid=document.querySelector("#film");vid.src=`${cfg.filmBasePath}${number}.mp4`;document.querySelector("#film-status").textContent=`If Film ${number} does not play, the reward is still earned. Tell your teacher so the file can be checked.`;filmDialog.showModal(); }
  document.querySelector("#close-film").onclick=()=>{document.querySelector("#film").pause();filmDialog.close();};
  function cleanForExport(){ const content={};missions.forEach(m=>content[m.id]={id:m.id,title:m.title,film:m.film,brief:m.brief,reading:m.reading,sources:(m.sources||[]).map(s=>({label:s.label||"Source",text:sourceText(s)})),questions:m.questions.map(q=>({id:q.id,kind:questionKind(q),prompt:q.prompt,options:q.options||[]})),writing:{prompt:m.writing?.prompt,stems:m.writing?.stems},criteria:m.criteria,sourceNote:m.sourceNote}); return {schemaVersion:"1.0",exportType:"festival_day_student_dossier",appVersion:cfg.appVersion,contentVersion:cfg.contentVersion,submission:{submissionId:state.submissionId,username:state.username,startedAt:state.startedAt,exportedAt:new Date().toISOString()},work:{responses:state.responses,approvals:state.approvals,requestedChanges:state.requestedChanges},missionContext:content}; }
  function download(){ save(); const data=cleanForExport(), safe=(state.username||"student").replace(/[^a-z0-9_-]/gi,"-").slice(0,32)||"student"; const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`festival-dossier-${safe}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000); saveStatus.textContent="Checkpoint downloaded. Keep it somewhere safe."; }
  document.querySelector("#download").onclick=download; username.addEventListener("input",save); document.querySelector("#reset").onclick=()=>{if(!confirm("Start again? Download a checkpoint first if you want to keep this work."))return;state={schemaVersion:"1.0",exportType:"festival_day_student_dossier",appVersion:cfg.appVersion,contentVersion:cfg.contentVersion,submissionId:cryptoId(),startedAt:new Date().toISOString(),username:"",responses:{},approvals:{},requestedChanges:{},savedAt:null};username.value="";save();view="map";render();};
  document.querySelector("#import").addEventListener("change",async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(data.schemaVersion!=="1.0"||data.exportType!=="festival_day_student_dossier")throw Error();if(!confirm("Import this checkpoint and replace work currently open on this device?"))return;state={...state,submissionId:data.submission?.submissionId||cryptoId(),username:data.submission?.username||"",startedAt:data.submission?.startedAt||new Date().toISOString(),responses:data.work?.responses||{},approvals:data.work?.approvals||{},requestedChanges:data.work?.requestedChanges||{}};username.value=state.username;save();view="map";render();}catch(_){alert("That file is not a Festival Day checkpoint.");}e.target.value="";});
  function render(){ username.value=state.username||username.value; if(view==="map")renderMap();else renderMission(); }
  load(); username.value=state.username||""; if(!missions.length){app.innerHTML="<p class='notice'>Mission files are still loading. Reload this page after the activity files are installed.</p>";return;}render();
})();
